version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        command: php artisan serve --host=0.0.0.0 --port=8000
        environment:
            DB_HOST: db
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: root

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
